replicaCount: 1

image:
  repository: fiware/pep-proxy
  tag: "8.4.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# Manteniamo la porta perché è usata strutturalmente nel deployment.yaml per il containerPort
pepProxy:
  port: 8080

ingress:
  enabled: false
  name: wilma-ingress
  className: ""
  annotations: {}
  hosts:
    - hosts:
        - host: iot.epsilonlab.internal
          paths:
            - path: /api
              pathType: Prefix

# Inizializziamo l'array vuoto per permettere l'iniezione dinamica
env: []